### ISSUE TITLE
CSV data links need updating

### ISSUE THREAD

**Issue by Lextuga007** [traffordDataLab/charticles#1]
The links no longer work as the data file is now to 2019:

accident <- read_csv("http://odata.tfgm.com/opendata/downloads/STATS19AccData20052019.csv") 
casualty <- read_csv("http://odata.tfgm.com/opendata/downloads/STATS19CasData20052019.csv")

was 

accident <- read_csv("http://odata.tfgm.com/opendata/downloads/STATS19AccData20052018.csv") 
casualty <- read_csv("http://odata.tfgm.com/opendata/downloads/STATS19CasData20052018.csv")

The script also fails saying "Error in geom_waffle(color = "#FFFFFF", size = 0.25, n_rows = 5, flip = TRUE) : 
  could not find function "geom_waffle"

**Comment by itsozz** [comment]
Hi, thanks very much for bringing this to our attention. Unfortunately it seems Transport for Greater Manchester who provide the data don't keep previous versions of the files, they simply update the data and change the filenames accordingly.  This will mean that the URLs will need to be changed each year.  However the code filters for the correct year (in this case the Charticle is referring to 2018) so simply updating the data URLs is all that's required.

Regarding the error for the geom_waffle function, I've put additional comments in the script file for this.  The function exists in v1.0.1 of the waffle package but the version on CRAN is v0.7.0, therefore you need to specify the repo with the higher version when installing the package.  I've made all these changes in commit 9882d433d02e146233b06d789e6500d6be3d940f which should hopefully resolve the issues.

I'll close this for now but please let us know if there's any further problems.  Thanks again for your contribution, really appreciated.
